events {}

http {
    # DNS interno di Docker: permette a Nginx di cercare i nomi dei servizi dinamicamente
    resolver 127.0.0.11 valid=30s;
    # Aumenta la dimensione massima dei file caricabili (importante per document-service)
    client_max_body_size 20M;

    server {
        listen 80;

        # Smistamento verso i microservizi (API)
        location /api/v1/users {
            proxy_pass http://user-service:8080;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        location /api/v1/gruppi {
            proxy_pass http://user-service:8080;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        location /api/v1/documents {
            set $upstream_doc document-service;
            proxy_pass http://$upstream_doc:8080;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        location /api/v1/search {
            set $upstream_search search-service;
            proxy_pass http://$upstream_search:8080;
            proxy_set_header Host $host;
        }

        location /api/v1/notifications {
            set $upstream_notification notification-service;
            proxy_pass http://$upstream_notification:8080;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        # Smistamento verso il Frontend (React)
        # Deve essere l'ultimo blocco perché cattura tutto il resto
        location / {
            proxy_pass http://frontend:80; 
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }
    }
}