server {
    listen 80;

    location / {
        root   /usr/share/nginx/html;
        index  index.html index.htm;
        # Questa riga è fondamentale per le rotte di React:
        try_files $uri $uri/ /index.html;
    }

    # Opzionale: Gestione degli errori
    # error_page   500 502 503 504  /50x.html;
    location = /50x.html {
        root   /usr/share/nginx/html;
    }
}